
FROM alpine:3.13.2 as kops
ARG VERSION
RUN apk add curl \
  && curl -L -s https://github.com/kubernetes/kops/releases/download/${VERSION}/kops-linux-amd64 -o /usr/local/bin/kops \
  && chmod +x /usr/local/bin/kops

FROM golang:alpine as golang
RUN apk add git \
  && go install github.com/google/go-jsonnet/cmd/jsonnet \
  && go install github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb \
  && go install github.com/brancz/gojsontoyaml

FROM landtech/ci-kubernetes:latest
COPY --from=kops /usr/local/bin/kops /usr/local/bin
COPY --from=golang /go/bin /usr/local/bin

