FROM node:13.10.1-alpine

ENV PATH="./node_modules/.bin:${PATH}"
ENV SHELL /bin/bash

COPY shared/deployment /usr/local/bin
COPY shared/semver.sh /usr/local/bin
COPY shared/core_deps.sh .
RUN ./core_deps.sh && rm core_deps.sh
