FROM node:18

ENV PATH="./node_modules/.bin:${PATH}"
ENV SHELL /bin/bash
ARG GITHUB_ACCESS_TOKEN=abc

RUN apt-get update
RUN apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config
RUN corepack enable
RUN yarn set version stable
RUN git clone --depth 1 https://$GITHUB_ACCESS_TOKEN@github.com/landtechnologies/apps.git
WORKDIR /apps
# RUN NODE_OPTIONS=--max_old_space_size=8192 yarn install 
# WORKDIR /
# RUN rm -rf /apps
